num_workers: 5
start_date: 2024-08-01
tasks:
  # Project Initiation and Planning
  - id: project_kickoff
    estimate:
      min: 2
      likely: 2.8
      max: 3
    dependencies: []

  - id: requirements_gathering
    estimate:
      min: 10
      likely: 13
      max: 15
    dependencies: [project_kickoff]

  - id: system_architecture_design
    estimate:
      min: 15
      likely: 18
      max: 20
    dependencies: [requirements_gathering]

  - id: database_design
    estimate:
      min: 5
      likely: 8
      max: 10
    dependencies: [system_architecture_design]

  # Frontend Development
  - id: ui_ux_design
    estimate:
      min: 20
      likely: 24
      max: 30
    dependencies: [requirements_gathering]

  - id: frontend_setup
    estimate:
      min: 3
      likely: 4.2
      max: 5
    dependencies: [ui_ux_design]

  - id: user_authentication_frontend
    estimate:
      min: 5
      likely: 6.1
      max: 10
    dependencies: [frontend_setup]

  - id: product_catalog_frontend
    estimate:
      min: 15
      likely: 17
      max: 25
    dependencies: [frontend_setup]

  - id: shopping_cart_frontend
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [frontend_setup]

  - id: checkout_process_frontend
    estimate:
      min: 15
      likely: 17
      max: 20
    dependencies: [shopping_cart_frontend]

  - id: user_profile_frontend
    estimate:
      min: 5
      likely: 6
      max: 10
    dependencies: [user_authentication_frontend]

  - id: search_functionality_frontend
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [product_catalog_frontend]

  # Backend Development
  - id: backend_setup
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies: [system_architecture_design, database_design]

  - id: user_authentication_backend
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [backend_setup]

  - id: product_catalog_backend
    estimate:
      min: 20
      likely: 25
      max: 30
    dependencies: [backend_setup]

  - id: shopping_cart_backend
    estimate:
      min: 15
      likely: 18
      max: 20
    dependencies: [backend_setup]

  - id: checkout_process_backend
    estimate:
      min: 20
      likely: 23
      max: 25
    dependencies: [shopping_cart_backend]

  - id: user_profile_backend
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [user_authentication_backend]

  - id: search_functionality_backend
    estimate:
      min: 15
      likely: 18
      max: 20
    dependencies: [product_catalog_backend]

  - id: payment_gateway_integration
    estimate:
      min: 10
      likely: 13
      max: 15
    dependencies: [checkout_process_backend]

  # API Development and Integration
  - id: api_design
    estimate:
      min: 5
      likely: 7.5
      max: 10
    dependencies: [system_architecture_design]

  - id: api_development
    estimate:
      min: 25
      likely: 32
      max: 35
    dependencies: [api_design, backend_setup]

  - id: api_documentation
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies: [api_development]

  # Testing
  - id: unit_testing
    estimate:
      min: 20
      likely: 25
      max: 30
    dependencies:
      [
        user_authentication_backend,
        product_catalog_backend,
        shopping_cart_backend,
        checkout_process_backend,
        user_profile_backend,
        search_functionality_backend,
      ]

  - id: integration_testing
    estimate:
      min: 15
      likely: 16
      max: 20
    dependencies: [unit_testing, api_development]

  - id: user_acceptance_testing
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [integration_testing]

  # Security and Performance
  - id: security_audit
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [integration_testing]

  - id: performance_optimization
    estimate:
      min: 15
      likely: 17
      max: 20
    dependencies: [integration_testing]

  # Deployment and Launch
  - id: deployment_planning
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies: [system_architecture_design]

  - id: staging_environment_setup
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies: [deployment_planning]

  - id: production_environment_setup
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [staging_environment_setup]

  - id: data_migration
    estimate:
      min: 10
      likely: 12
      max: 20
    dependencies: [production_environment_setup]

  - id: user_training
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies: [user_acceptance_testing]

  - id: final_deployment
    estimate:
      min: 5
      likely: 7
      max: 10
    dependencies:
      [
        user_acceptance_testing,
        security_audit,
        performance_optimization,
        data_migration,
        user_training,
      ]

  # Post-launch
  - id: post_launch_support
    estimate:
      min: 10
      likely: 12
      max: 15
    dependencies: [final_deployment]

  - id: project_retrospective
    estimate:
      min: 2
      likely: 2.8
      max: 3
    dependencies: [post_launch_support]
